services:
  db:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD_FILE=/run/secrets/demo_postgres_password
    - POSTGRES_DB=snowboards
    ports:
      - '5432:5432'
    secrets:
      - demo_postgres_password

  identity-api:
    build:
      context: ./Helpers/Identity.Api
      dockerfile: Dockerfile
      args:
        CERTIFICATE_PASSWORD: ${CERTIFICATE_PASSWORD}
    ports:
      - '5002:5002'
      - '5003:5003'
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    depends_on:
      - db
        
secrets:
  demo_postgres_password:
    file: ./Helpers/Identity.Api/FakeVault/DemoSecrets/demo_postgres_password.txt